
variable "name" { default = "my-app" } #name of your service
variable "aws_region" { default = "ap-southeast-2" } #ch
variable "comment" {default = "my-app resource - generated by maxrozen.com/2018/08/08/start-your-own-internet-business-with-react"}
variable "bucket_site" {default = "my-app-12345"}
output "API Gateway URL" {
  value = "${aws_api_gateway_deployment.ssr_deployment.invoke_url}"
}
output "S3_BUCKET" {
  value = "${aws_s3_bucket.site.bucket_domain_name}"
}
