
variable "name" { default = "recordmyweight" } #name of your service
variable "aws_region" { default = "ap-southeast-2" } #ch
variable "comment" {default = "recordmyweight resource - generated by maxrozen.com/2018/08/15/start-your-own-internet-business-with-react-part-2"}
variable "bucket_site" {default = "recordmyweightcom"}
variable "domain_name" {default = "recordmyweight.com"}

output "API Gateway URL" {
  value = "${aws_api_gateway_deployment.ssr_deployment.invoke_url}"
}
output "S3_BUCKET" {
  value = "${aws_s3_bucket.site.bucket_domain_name}"
}
